### ISSUE TITLE
How do you launch eww?

### ISSUE THREAD

**Issue by RayZ0rr** [is0n/dotfiles#1]
Can you share your eww launch script?

**Comment by is0n** [comment]
I have the following in my `autostart` script for herbstluftwm:
```shell
function launch_eww {
  eww daemon
  eww open bar
  ~/.config/eww/scripts/powermenu
  ~/.config/eww/scripts/dashboard
}

pgrep eww || launch_eww &
```

**Comment by RayZ0rr** [comment]
oops I didn't see that function. I thought it would be some script in your `PATH`
